# https://megalinter.io/configuration/
---
VALIDATE_ALL_CODEBASE: true

DISABLE:
  - SPELL
DISABLE_LINTERS:
  - DOCKERFILE_HADOLINT
  - MAKEFILE_CHECKMAKE
  - REPOSITORY_KICS
  - REPOSITORY_TRIVY

PLUGINS:
  - https://raw.githubusercontent.com/cdzombak/mega-linter-plugin-dockerfilelint/main/mega-linter-plugin-dockerfilelint/dockerfilelint.megalinter-descriptor.yml

SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: false
PRINT_ALPACA: false
