#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -eq 0 ]; then
	echo "[!] Pass input file names as arguments."
	exit 2
fi

for infname in "$@"
do
	echo "$infname ..."
	ffmpeg -i "$infname" -y -v 0 -vcodec copy -acodec alac "$infname.m4a"
done
