#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -eq 0 ]; then
	echo "[!] Pass input file names as arguments."
	exit 2
fi

for infname in "$@"
do
	echo "$infname ..."
	ffmpeg -i "$infname" -c:a aac -b:a 320k -c:v copy "$infname.m4a"
done
