#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -eq 0 ]; then
	echo "[!] Pass input file names as arguments."
	exit 2
fi

for infname in "$@"
do
	echo "$infname ..."
	ffmpeg -i "$infname" -movflags faststart -pix_fmt yuv420p -preset slow -codec:a aac -codec:v libx264 -b:a 160k -crf 18 "$infname.mp4"
done
