#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -eq 0 ]; then
	echo "[!] Pass input file names as arguments."
	exit 2
fi

for infname in "$@"
do
	outfname="$(echo "$infname" | rev | cut -d '.' -f2- | rev).png"
	echo "$infname -> $outfname ..."
	convert "$infname" "$outfname"
done
